[package]
name = "duckdb-sink"
group = "infinyon"
version = "0.1.1"
apiVersion = "0.1.0"
fluvio = "0.11.8"
description = "Duckdb sink connector"
license = "Apache-2.0"
visibility = "public"

[direction]
dest = true

[deployment]
binary = "duckdb-sink"

[custom]
name = "duckdb"
required = ["url"]

[custom.properties.url]
title = "Url"
description = "DuckDB connection url"
type = "string"
