name: Publish Hub PROD

permissions: read-all

on:
  workflow_dispatch:

jobs:
  linux:
    name: linux
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        rust-target:
          [
            aarch64-unknown-linux-gnu,
          ]
        os: [ubuntu-latest]
    env:
      CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse
    steps:
      - name: Install Fluvio
        run: |
          curl -fsS https://packages.fluvio.io/v1/install.sh | bash
          echo "$HOME/.fluvio/bin" >> $GITHUB_PATH
      - name: Install Rust ${{ matrix.rust }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.rust-target }}
          profile: minimal
          override: true
      - name: Install Fluvio CDK
        run: fluvio install cdk --develop
      - name: Fluvio Login
        run: fluvio cloud login --email ${{ secrets.PROD_HUB_USER_EMAIL }} --password ${{ secrets.PROD_HUB_USER_PASSWORD }}
      - uses: actions/checkout@v3
      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: "14.0"
      - name: install cross
        run: cargo install cross
      - name: Build
        env:
          GH_TOKEN: ${{ github.token }}
          TARGET: ${{ matrix.rust-target }}
        run:
          make cross_build
      - name: Publish
        run: |
          cdk publish --no-build \
            --public-yes \
            --target ${{ matrix.rust-target }} \
            -p duckdb-sink
