name: Publish Hub Dev

permissions: read-all

on:
  workflow_dispatch:

jobs:
  linux:
    name: linux
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        rust-target:
          [
            aarch64-unknown-linux-gnu,
          ]
        os: [ubuntu-latest]
    env:
      CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse
    steps:
      - name: Install Fluvio
        run: |
          curl -fsS https://packages.fluvio.io/v1/install.sh | bash
          echo "$HOME/.fluvio/bin" >> $GITHUB_PATH
      - name: Install Rust ${{ matrix.rust }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.rust-target }}
          profile: minimal
          override: true
      - name: Install Fluvio CDK
        run: fluvio install cdk --develop
      - name: Fluvio Login
        run: fluvio cloud login --email ${{ secrets.PROD_HUB_USER_EMAIL }} --password ${{ secrets.PROD_HUB_USER_PASSWORD }}
      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: "14.0"
      - name: Install zig
        run: ./actions/zig-install.sh ${{ matrix.os }}
      - name: install zigbuild
        run: cargo install cargo-zigbuild
      - name: Build
        run: |
          cargo zigbuild --release  --target ${{ matrix.rust-target }} -p duckdb-sink
      - name: Publish
        run: |
          cdk publish --no-build \
            --public-yes \
            --target ${{ matrix.rust-target }} \
            -p duckdb-sink

  macos:
    name: macos
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        rust-target: [x86_64-apple-darwin, aarch64-apple-darwin]
        os: [macos-latest]
    env:
      CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse
    steps:
      - name: Install Rust ${{ matrix.rust }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.rust-target }}
          profile: minimal
          override: true

      - name: Install Fluvio
        run: |
          curl -fsS https://packages.fluvio.io/v1/install.sh | bash
          echo "$HOME/.fluvio/bin" >> $GITHUB_PATH
      - name: Install Fluvio CDK
        run: fluvio install cdk --develop
      - name: Fluvio Login
        run: fluvio cloud login --email ${{ secrets.PROD_HUB_USER_EMAIL }} --password ${{ secrets.PROD_HUB_USER_PASSWORD }}
      - uses: actions/checkout@v3
      - name: Install zig
        run: ./actions/zig-install.sh ${{ matrix.os }}
      - name: install zigbuild
        run: cargo install cargo-zigbuild

      - name: Build
        run: |
          rustup target add ${{ matrix.rust-target }}
          cargo zigbuild --release  --target ${{ matrix.rust-target }} -p duckdb-sink
      - name: Publish
        run: |
          cdk publish --public-yes \
            --target ${{ matrix.rust-target }} \
            -p duckdb-sink
